# ==========================================
# Application
# ==========================================
spring.application.name=FlowLeave

# ==========================================
# Database Configuration
# ==========================================
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/flowleave_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mysql}

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensure Hibernate creates/updates the schema BEFORE data.sql runs
spring.jpa.defer-datasource-initialization=true

# ==========================================
# Server
# ==========================================
server.port=8080